form_settings:
  taxonomy_term:
    default_value: false
    disable: false
    hidden: false
  block_content:
    default_value: false
    disable: false
    hidden: false
  file:
    default_value: false
    disable: false
    hidden: false
  node:
    default_value: true
    disable: false
    hidden: false
  shortcut:
    default_value: false
    disable: false
    hidden: false
  user:
    default_value: false
    disable: false
    hidden: false
  menu_link_content:
    default_value: false
    disable: false
    hidden: false
  background_image:
    default_value: false
    disable: false
    hidden: false
  media:
    default_value: false
    disable: false
    hidden: false
  path_alias:
    default_value: false
    disable: false
    hidden: false
  webform_submission:
    default_value: false
    disable: false
    hidden: false
no_suffix: false
take_ownership: false
